### ISSUE TITLE
[Bug]: `PosixPath` has no method `startswith`

### ISSUE THREAD

**Issue by mtalexan** [MMMZZZZ/Jellyfin-Migrator#10]
[Lines 526 and 527 of of `jellyfin_migrator.py`](https://github.com/MMMZZZZ/Jellyfin-Migrator/blob/bc9df4195a687e9f46db18a7ed3a5494176bc45a/jellyfin_migrator.py#L526C1-L527C56) are trying to determine if the `Path` object (`d`) starts with a fixed prefix.  

```
Traceback (most recent call last):
  File "jellyfin_migrator.py", line 1273, in <module>
    process_files(
  File "jellyfin_migrator.py", line 995, in process_files
    target = get_target(
  File "jellyfin_migrator.py", line 822, in get_target
    target, idgaf1, idgaf2 = recursive_root_path_replacer(original_source, to_replace=replacements)
  File "jellyfin_migrator.py", line 520, in recursive_root_path_replacer
    and not d.startswith("https:") \
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

As shown on [line 514](https://github.com/MMMZZZZ/Jellyfin-Migrator/blob/bc9df4195a687e9f46db18a7ed3a5494176bc45a/jellyfin_migrator.py#L514), it needs `as_posix()` called on it first.
For example:
```patch
-                        and not d.startswith("https:") \
-                        and not d.startswith("http:") \
+                        and not d.as_posix().startswith("https:") \
+                        and not d.as_posix().startswith("http:") \
```

**Comment by mtalexan** [comment]
I see where this is coming from now.  The `recursive_root_path_replacer` is trying to combine the handling of `d` being a `Path` and it being a `str`.  But the two types require different functions for determining if it starts with a string.

So if I leave the described code as-is, it fails immediately with the traceback listed above when `d` is a `Path`.  But if I change it, it fails later when `update_db_table` calls it with `d` as a `str`:
```
Traceback (most recent call last):
  File "jellyfin_migrator.py", line 1291, in <module>
    process_files(
  File "jellyfin_migrator.py", line 1020, in process_files
    process_func(
  File "jellyfin_migrator.py", line 922, in process_file
    update_db_table(file=target, replace_dict=replacements, replace_func=replace_func, table=table, **kwargs)
  File "jellyfin_migrator.py", line 706, in update_db_table
    path, mo, ig = replace_func(path, replace_dict)
  File "jellyfin_migrator.py", line 528, in recursive_root_path_replacer
    and not d.as_posix().startswith("https:") \
AttributeError: 'str' object has no attribute 'as_posix'
```

The logic for `d` being `str` and `Path` has to be differentiated at least for this check, or it won't work.

**Comment by reeseovine** [comment]
having this same issue, running on Windows 10 with Python/IDLE 3.12.1

**Comment by connorjfarrell** [comment]
I was able to fix this issue for me by adding:
```
# Perform type check before deciding how to proceed
if isinstance(d, PosixPath):
    d = d.as_posix()
```
prior to the lines:

```
                # No need to consider all the Path("sometext") objects. This might not be 100%
                # accurate, but it eliminates 99.9999% of the false-positives. This output is
                # after all only to give you a hint whether you missed a path.
                # Also exclude URLs. Btw: pathlib can be quite handy for messing with URLs.
                if len(p.parents) > 1 \
                        and not d.startswith("https:") \
                        and not d.startswith("http:") \
                        and not to_replace.get("log_no_warnings", False):
                    print_log(f"No entry for this (presumed) path: {d}")
```

You will also need to update
`from pathlib import Path` to `from pathlib import Path, PosixPath`

**Comment by AmritP777** [comment]
> I was able to fix this issue for me by adding:
> 
> ```
> # Perform type check before deciding how to proceed
> if isinstance(d, PosixPath):
>     d = d.as_posix()
> ```
> 
> prior to the lines:
> 
> ```
>                 # No need to consider all the Path("sometext") objects. This might not be 100%
>                 # accurate, but it eliminates 99.9999% of the false-positives. This output is
>                 # after all only to give you a hint whether you missed a path.
>                 # Also exclude URLs. Btw: pathlib can be quite handy for messing with URLs.
>                 if len(p.parents) > 1 \
>                         and not d.startswith("https:") \
>                         and not d.startswith("http:") \
>                         and not to_replace.get("log_no_warnings", False):
>                     print_log(f"No entry for this (presumed) path: {d}")
> ```
> 
> You will also need to update `from pathlib import Path` to `from pathlib import Path, PosixPath`

would you mind validating what version of python / OS you had please? i'm wondering what other variables i have, as i get the exact same issue before and after making the changes you've mentioned there. thanks
