### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'is_relative_to'

### ISSUE THREAD

**Issue by vtmarik** [MMMZZZZ/Jellyfin-Migrator#16]
`Starting Jellyfin Database Migration
Current job from todo_list: C:\ProgramData\Jellyfin\Server\data\library.db
Traceback (most recent call last):
  File "jellyfin_migrator.py", line 1283, in <module>
    path_replacements=path_replacements,
  File "jellyfin_migrator.py", line 1005, in process_files
    no_log=job["no_log"],
  File "jellyfin_migrator.py", line 828, in get_target
    target, idgaf1, idgaf2 = recursive_root_path_replacer(original_source, to_replace=replacements)
  File "jellyfin_migrator.py", line 505, in recursive_root_path_replacer
    if p.is_relative_to(src):
AttributeError: 'WindowsPath' object has no attribute 'is_relative_to'`

Unsure what the actual issue is, i followed the instructions and made sure that the PATH checkbox was checked when I installed python.

**Comment by AmritP777** [comment]
did you ever get to the bottom of this? i have the exact same error.

**Comment by starexe** [comment]
I have also encountered this problem. Although, in my case, it said 'WindowsPath' object has no attribute 'startswith'. Any new enlightenment?
